/**
 * Generates Tiltfile content for a worktree.
 *
 * The generated Tiltfile reads all configuration from environment variables
 * (REPO_ROOT, PORT_BACKEND, PORT_ADJUSTER, PORT_FRONTEND) so a single
 * file can be reused across worktrees by varying the process env.
 */
export function generateTiltfile(): string {
  return `# Auto-generated by dev-proxy orchestrator — do not edit
# Ports and repo root are read from process environment variables.

REPO_ROOT = os.environ['REPO_ROOT']
PORT_BACKEND  = int(os.environ['PORT_BACKEND'])
PORT_ADJUSTER = int(os.environ['PORT_ADJUSTER'])
PORT_FRONTEND = int(os.environ['PORT_FRONTEND'])

print('  repo:     ' + REPO_ROOT)
print('  backend:  ' + str(PORT_BACKEND))
print('  adjuster: ' + str(PORT_ADJUSTER))
print('  frontend: ' + str(PORT_FRONTEND))

# ── Setup ────────────────────────────────────────────────────

local_resource(
    'pnpm-install',
    cmd='cd {} && pnpm install'.format(REPO_ROOT),
    labels=['setup'],
)

local_resource(
    'db-migrations',
    cmd='''
        cd {repo}/apps/backend
        OUTPUT=$(pnpm run cloneDB-fix-migrations 2>&1)
        echo "$OUTPUT"

        if echo "$OUTPUT" | grep -q "Run: pnpm deploy-db"; then
            echo ""
            echo "Migrations need to be applied, running deploy-db..."
            pnpm run deploy-db
        else
            echo ""
            echo "Database migrations are up to date"
        fi
    '''.format(repo=REPO_ROOT),
    labels=['setup'],
    resource_deps=['pnpm-install'],
)

local_resource(
    'adjuster-genTypes-init',
    cmd='cd {}/apps/adjuster && pnpm genTypes'.format(REPO_ROOT),
    labels=['setup'],
    resource_deps=['pnpm-install'],
)

# ── Apps ─────────────────────────────────────────────────────

local_resource(
    'backend',
    serve_cmd='cd {repo}/apps/backend && PORT={port} doppler run --preserve-env -- node --experimental-loader newrelic/esm-loader.mjs --require newrelic ./start-dev-server.js --no-notify --respawn --exit-child --rs --transpile-only src/server'.format(repo=REPO_ROOT, port=PORT_BACKEND),
    labels=['apps'],
    resource_deps=['db-migrations'],
    links=['http://localhost:{}'.format(PORT_BACKEND)],
)

local_resource(
    'adjuster',
    serve_cmd='cd {repo}/apps/adjuster && PORT={port} REACT_APP_ENDPOINT=http://localhost:{backend} doppler run --preserve-env -- pnpm exec parcel --watch-dir ../../ src/index.html'.format(repo=REPO_ROOT, port=PORT_ADJUSTER, backend=PORT_BACKEND),
    labels=['apps'],
    resource_deps=['db-migrations', 'adjuster-genTypes-init'],
    links=['http://localhost:{}'.format(PORT_ADJUSTER)],
)

local_resource(
    'frontend',
    serve_cmd='cd {repo}/apps/frontend && PORT={port} REACT_APP_ENDPOINT=http://localhost:{backend} doppler run --preserve-env -- pnpm exec parcel --watch-dir ../../ src/index.html'.format(repo=REPO_ROOT, port=PORT_FRONTEND, backend=PORT_BACKEND),
    labels=['apps'],
    resource_deps=['db-migrations'],
    links=['http://localhost:{}'.format(PORT_FRONTEND)],
)

# ── Tools (manual trigger) ───────────────────────────────────

local_resource(
    'backend-genTypes',
    cmd='cd {}/apps/backend && pnpm genTypes'.format(REPO_ROOT),
    labels=['tools'],
    auto_init=False,
)

local_resource(
    'adjuster-genTypes',
    cmd='cd {}/apps/adjuster && pnpm genTypes'.format(REPO_ROOT),
    labels=['tools'],
    auto_init=False,
)

local_resource(
    'clear-adjuster-cache',
    cmd='rm -rf {}/apps/adjuster/.parcel-cache && echo "Parcel cache cleared for adjuster"'.format(REPO_ROOT),
    labels=['tools'],
    auto_init=False,
)

local_resource(
    'clear-frontend-cache',
    cmd='rm -rf {}/apps/frontend/.parcel-cache && echo "Parcel cache cleared for frontend"'.format(REPO_ROOT),
    labels=['tools'],
    auto_init=False,
)
`;
}
